name: Node.js Build

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Pull the code from your repo
      - name: Checkout code
        uses: actions/checkout@v4
      # 2. Set up the Node environment
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm' # This caches your ~/.npm directory to speed up future runs
      # 3. Install dependencies strictly using the lockfile
      - name: Install dependencies
        run: npm ci
      # 4. Run the build script defined in your package.json
      - name: Run build
        run: npm run build
      # 5. Run tests
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          # In addition to the stdout, save the results as snyk.json
          args: --json-file-output=snyk-results.json
      # 6. Run security gating
      - name: Run snyk-filter gating
        uses: gwnlng/snyk-filter-gate-action/.github/actions/snyk-filter-gate@main
        with:
          snyk-json-path: snyk-results.json   # required, default is snyk.json
          output-json: true

      # 7. Run security gating with redirected outputs
      - name: Run snyk-filter gating with redirected outputs
        uses: gwnlng/snyk-filter-gate-action/.github/actions/snyk-filter-gate@feat/redirected-outputs
        id: snyk-filter-gate
        continue-on-error: true
        with:
          snyk-json-path: snyk-results.json   # required, default is snyk.json
          output-json: true
          json-file-output: snyk-filter-results.json

      # 8. Convert snyk-filter-results to HTML
      - name: Download and convert Snyk filter results to HTML
        if: steps.snyk-filter-gate.outcome == 'failure'
        run: |
          # Download latest snyk-to-html binary for Linux
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/snyk/snyk-to-html/releases/latest | jq -r '.assets[] | select(.name | contains("linux")) | .browser_download_url' | head -n 1)
          wget -O snyk-to-html "$LATEST_RELEASE"
          chmod +x snyk-to-html
          ./snyk-to-html -i snyk-filter-results.json -o snyk-filter-results.html
