name: Node.js Build

on:
  push:
  pull_request:
    branches: [ "main" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-test:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # 1. Pull the code from your repo
      - name: Checkout code
        uses: actions/checkout@v5
      # 2. Set up the Node environment
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm' # This caches your ~/.npm directory to speed up future runs
      # 3. Install dependencies strictly using the lockfile
      - name: Install dependencies
        run: npm ci
      # 4. Run the build script defined in your package.json
      - name: Run build
        run: npm run build
      # 5. Run tests
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          # In addition to the stdout, save the results as snyk.json
          args: --json-file-output=snyk-results.json
      # 6. Run security gating
      # - name: Run snyk-filter gating
      #   uses: gwnlng/snyk-filter-gate-action/.github/actions/snyk-filter-gate@main
      #   with:
      #     snyk-json-path: snyk-results.json   # required, default is snyk.json
      #     output-json: true

      # 7. Run security gating with redirected outputs
      - name: Run snyk-filter gating with redirected outputs
        uses: gwnlng/snyk-filter-gate-action/.github/actions/snyk-filter-gate@feat/redirected-outputs
        id: snyk-filter-gate
        continue-on-error: true
        with:
          snyk-json-path: snyk-results.json   # required, default is snyk.json
          output-json: true
          json-file-output: snyk-filter-results.json

      # 8a. Convert snyk-filter-results to HTML
      - name: Download and convert Snyk filter results to HTML
        if: steps.snyk-filter-gate.outcome == 'failure'
        run: |
          # Download latest snyk-to-html binary for runner OS
          npm install -g snyk-to-html
          snyk-to-html -i snyk-filter-results.json -o snyk-filter-results.html
          echo "SNYK_HTML_REPORT=snyk-filter-results.html" >> $GITHUB_ENV

      # 8b. still need a html report as a provenance of the gating result, even if the gate is passed (i.e. no vulnerabilities found)
      - name: Download and convert Snyk filter results to HTML
        if: steps.snyk-filter-gate.outcome == 'success'
        run: |
          # Download latest snyk-to-html binary for runner OS without using npm
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/snyk/snyk-to-html/releases/latest | jq -r '.assets[] | select(.name | contains("linux")) | .browser_download_url' | head -n 1)
          wget -O snyk-to-html "$LATEST_RELEASE"
          chmod +x snyk-to-html
          ./snyk-to-html -i snyk-results.json -o snyk-results.html
          echo "SNYK_HTML_REPORT=snyk-results.html" >> $GITHUB_ENV

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: snyk-security-report
          path: ${{ env.SNYK_HTML_REPORT }}

      - name: Create Snyk Security Report in Job Summary
        run: |
          # Construct the URL to the artifacts tab.
          # Note: A direct public link to the *file* within the artifact is not straightforward
          # without using the GitHub API and authentication. This provides a link to the artifact itself.
          ARTIFACT_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          GITHUB_REPOSITORY_NAME="${GITHUB_REPOSITORY#*/}"
          SNYK_REPORT_URL="https://${{ github.repository_owner }}.github.io/${GITHUB_REPOSITORY_NAME}/${{ github.run_id }}/index.html"

          # Append a Markdown link to the GITHUB_STEP_SUMMARY file
          echo "View the [Snyk Security HTML report]($SNYK_REPORT_URL)" >> $GITHUB_STEP_SUMMARY
          echo "[Download snyk-security-report artifact]($ARTIFACT_URL)" >> $GITHUB_STEP_SUMMARY

      - name: Copy Snyk HTML report to Pages run directory
        run: |
          mkdir -p "runs/${{ github.run_id }}"
          cp ${{ env.SNYK_HTML_REPORT }} "runs/${{ github.run_id }}/index.html"

      # - name: Setup Pages
      #   uses: actions/configure-pages@v5

      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     # Upload entire repository
      #     path: './runs'

      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./runs/${{ github.run_id }}
          destination_dir: runs/${{ github.run_id }}

      - name: Notify Snyk Security Check Result
        if: steps.snyk-filter-gate.outcome == 'failure'
        run: |
           echo "Please review the [Snyk report](${{ env.SNYK_HTML_REPORT }}) for details."
           exit 1
